Repository BE-Team2/Movie, pull requests merged in 2023-01, with the labels that each got.

#17 간단한 멤버 회원가입 기능 구현 #16-signup
  src/main/java/com/example/movie/login/controller/SignupController.java
  src/main/java/com/example/movie/login/dto/MemberDTO.java
  src/main/java/com/example/movie/login/entity/Member.java
  src/main/java/com/example/movie/login/repository/SignupRepository.java
  src/main/java/com/example/movie/login/service/SignupService.java
  src/main/java/com/example/movie/mapper/MemberMapper.java
  src/main/resources/member.sql
  src/main/resources/mybatis-mapper/MemberMapper.xml
Labels: enhancement

#21 Feature/#19 login
  src/main/java/com/example/movie/login/controller/LoginController.java
  src/main/java/com/example/movie/login/dto/MemberDTO.java
  src/main/java/com/example/movie/login/entity/Member.java
  src/main/java/com/example/movie/login/repository/LoginRepository.java
  src/main/java/com/example/movie/login/service/LoginService.java
  src/main/java/com/example/movie/mapper/MemberMapper.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/resources/member.sql
  src/main/resources/mybatis-mapper/MemberMapper.xml
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: enhancement

#23 Feature/#19 login
  src/main/java/com/example/movie/aop/AuthAspect.java
  src/main/java/com/example/movie/login/controller/LoginController.java
  src/main/java/com/example/movie/login/service/LoginService.java
  src/main/java/com/example/movie/login/service/SignupService.java
Labels: enhancement

#24 Feature/#18 comment&movie
  src/main/java/com/example/movie/controller/CommentController.java
  src/main/java/com/example/movie/controller/MovieController.java
  src/main/java/com/example/movie/dto/CommentDTO.java
  src/main/java/com/example/movie/dto/MovieDTO.java
  src/main/java/com/example/movie/mapper/CommentMapper.java
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/CommentRepository.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/CommentService.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/mybatis-mapper/CommentMapper.xml
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/templates/movie.html
  src/main/resources/templates/movie_detail.html
Labels: enhancement

#25 gitflow-feature-stash: emergency
  src/main/java/com/example/movie/login/service/LoginService.java
  src/main/java/com/example/movie/login/service/SignupService.java
Labels: documentation

#26 Member Entity 삭제
  src/main/java/com/example/movie/login/dto/MemberDTO.java
  src/main/java/com/example/movie/login/entity/Member.java
  src/main/java/com/example/movie/login/repository/SignupRepository.java
  src/main/java/com/example/movie/login/service/LoginService.java
  src/main/java/com/example/movie/login/service/SignupService.java
  src/main/java/com/example/movie/mapper/MemberMapper.java
  src/main/resources/mybatis-mapper/MemberMapper.xml
Labels: enhancement

#28 Feature/#27 - 메인화면 접근 시 영화 정보 테이블에 Insert
  build.gradle
  libs/kobis-opcl-rest-v1.0.jar
  src/main/java/com/example/movie/api/BoxOfficeApi.java
  src/main/java/com/example/movie/dto/DailyMovieDTO.java
  src/main/java/com/example/movie/dto/MovieDTO.java
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/mybatis-mapper/MovieMapper.xml
Labels: enhancement

#34 Feature/#33 DTO 수정, api 예외처리
  src/main/java/com/example/movie/api/BoxOfficeApi.java
  src/main/java/com/example/movie/controller/MovieController.java
  src/main/java/com/example/movie/dto/DailyMovieDTO.java
  src/main/java/com/example/movie/dto/MovieDTO.java
Labels: bug

#39 #30 서비스단 버그 긴급수정하였습니다.
  src/main/java/com/example/movie/login/service/LoginService.java
  src/main/java/com/example/movie/login/service/SignupService.java
Labels: bug

#41 Mypage conflict 해결
  src/main/java/com/example/movie/controller/CommentController.java
  src/main/java/com/example/movie/login/controller/LoginController.java
  src/main/java/com/example/movie/login/service/LoginService.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/BoardRepository.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/MemberService.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/mybatis-mapper/CommentMapper.xml
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/mybatis-mapper/OrderMapper.xml
  src/main/resources/templates/mypage/myPage.html
Labels: bug

#44 #43 - Logback 설정
  src/main/java/com/example/movie/aop/AuthAspect.java
  src/main/java/com/example/movie/aop/LogAdvice.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: enhancement

#42 Feature/#31 메인화면 구성
  src/main/java/com/example/movie/api/BoxOfficeApi.java
  src/main/java/com/example/movie/dto/MovieDTO.java
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/swiper.css
  src/main/resources/static/icons/icon_age@1.png
  src/main/resources/static/icons/icon_age@2.png
  src/main/resources/static/icons/icon_m@1.png
  src/main/resources/static/icons/icon_m@2.png
  src/main/resources/static/icons/star.png
  src/main/resources/static/image/bg01@1.jpg
  src/main/resources/static/image/card01.jpg
  src/main/resources/static/image/card02.jpg
  src/main/resources/static/image/card03.jpg
  src/main/resources/static/image/close.svg
  src/main/resources/static/image/down.svg
  src/main/resources/static/image/grandOpenBanner.png
  src/main/resources/static/image/grandOpenBar.png
  src/main/resources/static/js/custom.js
  src/main/resources/static/js/ie-checker.js
  src/main/resources/static/js/iframe_api.js
  src/main/resources/static/js/jquery.min_1.12.4.js
  src/main/resources/static/js/modernizr-custom.js
  src/main/resources/static/js/movie.js
  src/main/resources/static/js/swiper.min.js
  src/main/resources/templates/index.html
Labels: enhancement

#47 #46 - mypage 관련 오류수정
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/page/controller/MyPageController.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/mybatis-mapper/MovieMapper.xml
Labels: bug

#49 Develop
  src/main/java/com/example/movie/login/controller/LoginController.java
  src/main/java/com/example/movie/page/controller/MyPageController.java
  src/main/resources/logback-spring.xml
  src/main/resources/static/js/custom.js
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage/myPage.html
  src/main/resources/templates/mypage/mypage.html
Labels: enhancement

#51 #50 - 게시판API수정
  src/main/java/com/example/movie/controller/BoardController.java
  src/main/java/com/example/movie/mapper/BoardMapper.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/BoardRepository.java
  src/main/java/com/example/movie/service/BoardService.java
  src/main/resources/mybatis-mapper/BoardMapper.xml
Labels: enhancement

#53 Develop (영화List페이지 및 영화상세페이지 개발)
  src/main/java/com/example/movie/aop/AuthAspect.java
  src/main/java/com/example/movie/controller/CommentController.java
  src/main/java/com/example/movie/controller/MovieController.java
  src/main/java/com/example/movie/dto/CommentDTO.java
  src/main/java/com/example/movie/login/repository/LoginRepository.java
  src/main/java/com/example/movie/login/service/LoginService.java
  src/main/java/com/example/movie/mapper/CommentMapper.java
  src/main/java/com/example/movie/mapper/MemberMapper.java
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/page/controller/MyPageController.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/CommentRepository.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/CommentService.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/main/resources/mybatis-mapper/CommentMapper.xml
  src/main/resources/mybatis-mapper/MemberMapper.xml
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/templates/movie.html
  src/main/resources/templates/movie_detail.html
  src/test/java/com/example/movie/controller/MovieControllerTest.java
Labels: enhancement

#62 #61 이상한 버그 수정
  src/main/java/com/example/movie/aop/AuthAspect.java
  src/main/java/com/example/movie/config/SecurityConfig.java
  src/main/resources/templates/login.html
Labels: enhancement

#63 #35 - Board뷰
  src/main/resources/templates/board.html
  src/main/resources/templates/boardDetail.html
  src/main/resources/templates/boardInsert.html
  src/main/resources/templates/boardUpdate.html
Labels: enhancement

#64 #56 - 영화 상세페이지 수정 : 이미지, 시놉시스 변경 및 추가
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/templates/movie_detail.html
Labels: enhancement

#66 #65 - mypage session 연결 바꾸기, 영화 포스터 가져오는 코드 정리
  src/main/java/com/example/movie/aop/LogAdvice.java
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/page/controller/MyPageController.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/application.properties
  src/main/resources/mybatis-mapper/CommentMapper.xml
  src/main/resources/mybatis-mapper/MemberMapper.xml
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/mybatis-mapper/OrderMapper.xml
  src/main/resources/templates/mypage/mypage-th.html
  src/main/resources/templates/mypage/user-order-th.html
Labels: bug

#68 67-insertBoardByAuthentication
  src/main/java/com/example/movie/controller/BoardController.java
  src/main/resources/templates/boardInsert.html
Labels: enhancement

#70 #69-insertReplyByAuthentication
  src/main/java/com/example/movie/controller/BoardController.java
  src/main/resources/templates/boardDetail.html
Labels: enhancement

#72 무비 접근 해결 실패
  src/main/java/com/example/movie/config/SecurityConfig.java
Labels: enhancement

#74 #73 - Swagger 추가, 예매 내역 사진 클릭 시 영화 상세 페이지로 이동 기능 구현
  src/main/java/com/example/movie/admin/controller/AdminController.java
  src/main/java/com/example/movie/admin/controller/AdminPageController.java
  src/main/java/com/example/movie/admin/dto/AdminDTO.java
  src/main/java/com/example/movie/admin/repository/AdminRepository.java
  src/main/java/com/example/movie/admin/service/AdminService.java
  src/main/java/com/example/movie/config/SecurityConfig.java
  src/main/java/com/example/movie/config/SwaggerConfig.java
  src/main/java/com/example/movie/controller/CommentController.java
  src/main/java/com/example/movie/controller/MemberController.java
  src/main/java/com/example/movie/controller/OrderController.java
  src/main/java/com/example/movie/controller/TheaterController.java
  src/main/java/com/example/movie/map/controller/MapController.java
  src/main/java/com/example/movie/mapper/AdminMapper.java
  src/main/java/com/example/movie/page/controller/MyPageController.java
  src/main/resources/mybatis-mapper/AdminMapper.xml
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/my.html
  src/main/resources/templates/mypage/mypage-th.html
  src/main/resources/templates/mypage/user-order-th.html
Labels: enhancement

#75 SecurityConfig 파일 긴급수정
  src/main/java/com/example/movie/config/SecurityConfig.java
Labels: bug

#76 Feature/#55 movie (movie 메인(리스트)페이지 수정)
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/resources/templates/movie.html
  src/main/resources/templates/movies.html
Labels: enhancement

#80 #79 - 로그인에 따른 버튼 변경, style.css 파일 정리
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/resources/logback-spring.xml
  src/main/resources/static/css/style.css
  src/main/resources/templates/index.html
Labels: enhancement

#81 #57 - 영화 상세페이지 : Comment 에서 Authentication(유저 권한) 관련 처리하기
  src/main/java/com/example/movie/config/SecurityConfig.java
  src/main/java/com/example/movie/controller/CommentController.java
  src/main/java/com/example/movie/dto/CommentDTO.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/resources/mybatis-mapper/CommentMapper.xml
  src/main/resources/templates/movie_detail.html
Labels: enhancement

#83 #82 - index 화면 swagger추가 & index.html 수정
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/resources/templates/index.html
Labels: enhancement

#85 84 - editDeleteButton
  src/main/java/com/example/movie/controller/BoardController.java
  src/main/resources/templates/boardDetail.html
Labels: bug

#86 #71 - Swagger 추가 및 PageController 없어진 @Autowired 추가
  src/main/java/com/example/movie/controller/CommentController.java
  src/main/java/com/example/movie/controller/MovieController.java
  src/main/java/com/example/movie/page/controller/PageController.java
Labels: enhancement

#87 Develop
  src/main/java/com/example/movie/config/SecurityConfig.java
Labels: enhancement

#88 류선 예매 기능 PR
  build.gradle
  src/main/java/com/example/movie/aop/LogAdvice.java
  src/main/java/com/example/movie/controller/TicketController.java
  src/main/java/com/example/movie/dto/InfoDTO.java
  src/main/java/com/example/movie/dto/TicketDTO.java
  src/main/java/com/example/movie/mapper/TicketMapper.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/TicketRepository.java
  src/main/java/com/example/movie/service/TicketService.java
  src/main/resources/application.properties
  src/main/resources/mybatis-mapper/TicketMapper.xml
  src/main/resources/static/css/resett.css
  src/main/resources/static/css/seat.css
  src/main/resources/static/css/showticket.css
  src/main/resources/static/css/stylee.scss
  src/main/resources/static/css/ticket.css
  src/main/resources/static/image/barcode.png
  src/main/resources/static/image/facam.PNG
  src/main/resources/static/image/me.PNG
  src/main/resources/static/image/reserve.PNG
  src/main/resources/static/image/twojo.PNG
  src/main/resources/static/images/barcode.png
  src/main/resources/static/images/reserve.PNG
  src/main/resources/static/js/kakao.js
  src/main/resources/static/js/seat.js
  src/main/resources/static/js/ticket.js
  src/main/resources/templates/index.html
  src/main/resources/templates/payComplete.html
  src/main/resources/templates/payticket.html
  src/main/resources/templates/seat.html
  src/main/resources/templates/ticket.html
  src/test/java/com/example/movie/controller/MovieControllerTest.java
  src/test/java/com/example/movie/controller/TicketControllerTest.java
Labels: enhancement

#90 #89 - index.htm 내의 head, header, footer 파일로 분리함.
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
Labels: enhancement

#92 Develop
  src/main/java/com/example/movie/aop/LogAdvice.java
  src/main/java/com/example/movie/controller/OrderController.java
  src/main/java/com/example/movie/controller/TicketController.java
  src/main/java/com/example/movie/dto/OrderDTO.java
  src/main/java/com/example/movie/map/controller/MapController.java
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/mapper/OrderMapper.java
  src/main/java/com/example/movie/mapper/TheaterMapper.java
  src/main/java/com/example/movie/mapper/TicketMapper.java
  src/main/java/com/example/movie/page/controller/MyPageController.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/repository/OrderRepository.java
  src/main/java/com/example/movie/repository/TheaterRepository.java
  src/main/java/com/example/movie/repository/TicketRepository.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/java/com/example/movie/service/OrderService.java
  src/main/java/com/example/movie/service/TheaterService.java
  src/main/java/com/example/movie/service/TicketService.java
  src/main/resources/logback-spring.xml
  src/main/resources/mybatis-mapper/OrderMapper.xml
  src/main/resources/mybatis-mapper/TheaterMapper.xml
  src/main/resources/mybatis-mapper/TicketMapper.xml
  src/main/resources/templates/mypage/mypage-th.html
  src/main/resources/templates/mypage/user-order-th.html
Labels: enhancement

#94 Movie 프로젝트 README.md 파일 추가
  README.md
Labels: documentation

#99 #98 - api -> db 업데이트 오류
  src/main/java/com/example/movie/api/BoxOfficeApi.java
  src/main/resources/mybatis-mapper/MovieMapper.xml
Labels: enhancement

#100 Feature/#100 ticket ajax
  README.md
  src/main/java/com/example/movie/controller/TicketController.java
  src/main/java/com/example/movie/dto/TheaterDTO.java
  src/main/java/com/example/movie/mapper/TheaterMapper.java
  src/main/java/com/example/movie/repository/TheaterRepository.java
  src/main/java/com/example/movie/service/TheaterService.java
  src/main/resources/mybatis-mapper/TheaterMapper.xml
  src/main/resources/static/css/seat.css
  src/main/resources/static/css/ticket.css
  src/main/resources/static/js/seat.js
  src/main/resources/static/js/ticket.js
  src/main/resources/templates/mypage/common/nav.html
  src/main/resources/templates/seat.html
  src/main/resources/templates/ticket.html
Labels: enhancement

#102 #101 - api에서 null 값 전달 시 발생되는 오류 수정
  src/main/java/com/example/movie/api/BoxOfficeApi.java
  src/main/java/com/example/movie/mapper/MovieMapper.java
  src/main/java/com/example/movie/page/controller/PageController.java
  src/main/java/com/example/movie/repository/MovieRepository.java
  src/main/java/com/example/movie/service/MovieService.java
  src/main/resources/mybatis-mapper/MovieMapper.xml
  src/main/resources/static/image/image_ready.jpeg
Labels: enhancement
